name:                create-app
version:             0.1.0.0
github:              "smaccoun/build"
license:             BSD3
author:              "Steven MacCoun"
maintainer:          "theraccoun@gmail.com"
copyright:           "2018 Steven MacCoun"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/smaccoun/build#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- system-filepath
- text

library:
  source-dirs: src

executables:
  create-app:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - create-app

tests:
  build-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - create-app
