apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: example-app-backend
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: "RollingUpdate"  
  selector:
    matchLabels:
      app: "example-app"
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: "example-app"
        tier: backend
        track: stable
    spec:
      containers:
        - name: "example-app-backend"
          image: "smaccoun/example-app-backend:7861b7c7a480758d70f85a6f2a374bfabce4249c
"
          envFrom:
            - configMapRef:
                name: "example-app-envvars" 
          terminationMessagePath: "/tmp/my-log"   
          resources:
            requests:
              memory: 10Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /health
              port: external
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: external
            initialDelaySeconds: 5
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              name: "external"
              protocol: "TCP"
