apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: example-app
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: example-app
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: example-app
        tier: frontend
        track: stable
    spec:
      containers:
      - name: example-app-frontend
        image: "smaccoun/example-app-frontend:5fd50fdd8abcce6370e6e6cf77b6e8fc8419fbad
"
        ports:
            - containerPort: 3000
              name: "external"
              protocol: "TCP"
        
